### ISSUE TITLE
An error message that could be enhanced

### ISSUE THREAD

**Issue by JulienPalard** [mbarkhau/bumpver#157]
Hi Manuel, thanks for bumpver! I'm trying it today and found a strange error message:

First, something normal:

```
$ bumpver test '21.3.17' 'YY.MM.DD'
New Version: 21.3.18
```

I'm happy!

Now I'm trying to re-bump the same version the same day, it can't work, I know:

```
$ bumpver test '21.3.18' 'YY.MM.DD'
ERROR   - Invalid arguments or pattern, version did not change.
ERROR   - Invalid version '21.3.18' and/or pattern 'YY.MM.DD'.
```

The "version did not change." error is usefull, but the "Invalid version '21.3.18' and/or pattern 'YY.MM.DD'" is missleading, I though I had an error in my version or my pattern.

**Comment by mbarkhau** [comment]
Yes I think the second message is a general error message generated as a catchall and should probably be omitted.

**Comment by mbarkhau** [comment]
Fixed with: https://pypi.org/project/bumpver/2021.1110/
