### ISSUE TITLE
PYTAGNUM used but not documented

### ISSUE THREAD

**Issue by JulienPalard** [mbarkhau/bumpver#158]
A lot of examples do use PYTAGNUM in the README, but it does not looks documented.

**Comment by JulienPalard** [comment]
I bet it is `rc1, rc2, rc3, ...` (as documented for `--tag-num`)?

**Comment by mbarkhau** [comment]
This is a misreading. It's `PYTAG` followed by `NUM` with no white-space between. You can use `--tag` to control the `TAG` and `PYTAG` parts, `--tag-num` to increment the `NUM` part.

Do you have a suggestion how to update the README to reflect this? We could add it to the [part overview](https://github.com/mbarkhau/bumpver#part-overview) as if it were a part, and just say something like "`PYTAG` and `NUM` with no white-space between".
