### ISSUE TITLE
Ability to just insert {new_version} in files

### ISSUE THREAD

**Issue by awtimmering** [mbarkhau/bumpver#161]
Feature request rather than issue: Would it be an idea to add the ability to just insert {new_version} in files - or is that potentially already possible?
Use case in mind is release notes / changelog, where you could keep a running log of changes, i.e.:
```
{new_version}:
  - feature a
  - feature b

2021.1001-alpha:
 - some previously implemented feature
 - this version number should remain untouched
```
to just have the blank filled un while bumping the version on the git tag etc.

**Comment by mbarkhau** [comment]
> is that potentially already possible?

Not at the moment no. Off the top of my head, I can't think of a reasonable way to implement this. It goes against the grain of how bumpver works.

I'm open to suggestions.

**Comment by awtimmering** [comment]
Fair point - it is hard to see how it would fit vs pattern recognition of the current version in files. Let's close for now - will also give it some thought when I have some spare cycles.
