### ISSUE TITLE
Incorrect version comparison when updating from vcs tag

### ISSUE THREAD

**Issue by timoludwig** [mbarkhau/bumpver#174]
The version check in `_update_cfg_from_vcs()` just does a regular string comparison, which does not work when the version numbers are not zero-padded:

https://github.com/mbarkhau/bumpver/blob/328ef5c10a8b1f810b4bf3a28d1e5b4e8fdab3aa/src/bumpver/cli.py#L668

E.g., I use the version pattern [YYYY.MM.INC0[-TAG]](https://github.com/digitalfabrik/integreat-cms/blob/a36abd455630445c67c8f4905bdf26546a77ac07/setup.cfg#L76) and have multiple local alpha versions which I don't commit to the vcs, but just use to publish dev versions to [test.pypi.org](https://test.pypi.org/project/integreat-cms/#history). However, this workflow failed today, because the tools thinks that the version from my git tag `2022.3.2` is newer than my local alpha version `2022.3.10a0`.

Because `"2022.3.9a0" <= "2022.3.2"` is `False`, the [previous build succeeded](https://app.circleci.com/pipelines/github/digitalfabrik/integreat-cms/3878/workflows/430624ec-0c2c-471a-a96e-105623be7514/jobs/30884) and `"2022.3.10a0" <= "2022.3.2"` is `True`, it does not allow me to bump my version any further than that and [sets the version back to 2022.3.3-alpha](https://app.circleci.com/pipelines/github/digitalfabrik/integreat-cms/3887/workflows/6a1c8a5b-171c-4b20-8acc-6e68ce8547b1/jobs/30969), which causes pypi [to fail](https://app.circleci.com/pipelines/github/digitalfabrik/integreat-cms/3887/workflows/6a1c8a5b-171c-4b20-8acc-6e68ce8547b1/jobs/30975) because this version already exists.

I would really appreciate any help and would also try to fix this if you point me into the right direction.

**Comment by mbarkhau** [comment]
Good catch. You can have a look at the function [`parse_version(version: str) -> typ.Any`](https://github.com/mbarkhau/bumpver/blob/master/src/bumpver/version.py#L12).

So you might be able to change that line:

```diff
- if latest_version_tag <= cfg.current_version: 
+ if version.parse_version(latest_version_tag) <= version.parse_version(cfg.current_version): 
```

**Comment by mbarkhau** [comment]
Uploaded to pypi
