### ISSUE TITLE
file_pattern conflicts with dependencies

### ISSUE THREAD

**Issue by sparktx-adam-gleason** [mbarkhau/bumpver#181]
I have the following `file_patterns` under `[tool.bumpver.file_patterns]' in my pyproject.toml file
- `"pyproject.toml" = ['current_version = "{version}"', 'version = "{version}"']`

I'm seeing a conflict with dependencies running `bumpver update --dry --minor` command

```
...
-django-reversion = "5.0.0"
+django-reversion = "0.6.0"
...
```
`'version = "{version}"'` pattern is a subpattern within `django-reversion = "5.0.0"`

Is there a way to limit match to full pattern and not match a subpattern?

**Comment by mbarkhau** [comment]
I gave it a try to use regexp syntax in file patterns and the detection appears to work. The replacement however does not, as the regex characters are added as literals.

```
[bumpver:file_patterns]
setup.cfg =
    ^current_version = "{version}"$
```

```diff
 [bumpver]
-current_version = "2022.1117"
+^current_version = "2022.1118"$
 version_pattern = "YYYY.BUILD[-TAG]"
```

I've made a patch so it now strips replaces these characters before rewriting: ``^$``.

```diff
 [bumpver]
-current_version = "2022.1117"
+current_version = "2022.1118"
 version_pattern = "YYYY.BUILD[-TAG]"
```

**Comment by mbarkhau** [comment]
I just pushed 2022.1118, hope it helps with your use-case.

**Comment by sparktx-adam-gleason** [comment]
🙌  Perfect this works well for my use case.
