### ISSUE TITLE
bumpver update --patch

### ISSUE THREAD

**Issue by jinfagang** [mbarkhau/bumpver#194]
It does update setup.cfg iteself??

**Comment by jinfagang** [comment]
How can I update setup.cfg itself so that I don't need update it manually??
+

**Comment by jinfagang** [comment]
@mbarkhau  this is my config:

```
[egg_info]
tag_build = 
tag_date = 0


[bumpver]
current_version = "3.0.1"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = True
tag = True
push = True

[bumpver:file_patterns]
alfred/version.py =
  __version__ = "{version}"
setup.cfg =
    current_version = "{version}"
setup.py =
    "{version}"
    "{pep440_version}"
README.md =
    {version}
    {pep440_version}


```

it was already in setup.cfg, but I run `bumpver update --patch`, it doesn't udpate cfg file

**Comment by jinfagang** [comment]
output

```
bumpver update --patch                                                                                 main
INFO    - fetching tags from remote (to turn off use: -n / --no-fetch)
INFO    - Old Version: 3.0.1
INFO    - New Version: 3.0.2
ERROR   - No match for pattern '__version__ = "MAJOR.MINOR.PATCH"'
ERROR   -
# https://regex101.com/?flavor=python&flags=gmx&regex=__version__%5B%20%5D%3D%5B%20%5D%5C%22%0A%28%3FP%3Cmajor%3E%5B0-9%5D%2B%29%0A%5C.%0A%28%3FP%3Cminor%3E%5B0-9%5D%2B%29%0A%5C.%0A%28%3FP%3Cpatch%3E%5B0-9%5D%2B%29%0A%5C%22
regex = re.compile(r"""
    __version__[ ]=[ ]\"
    (?P<major>[0-9]+)
    \.
    (?P<minor>[0-9]+)
    \.
    (?P<patch>[0-9]+)
    \"
""", flags=re.VERBOSE)
ERROR   - Invalid pattern(s)
```

**Comment by mbarkhau** [comment]
In future, you may find, that you will have your problems solved more quickly, if you start with and focus on the error messages.

As the error message states, the pattern for the file `alfred/version.py` doesn't match anything. You can click on the link and paste your file contents in the "TEST STRING" box to see where the issue might be.

**Comment by jinfagang** [comment]
@mbarkhau Sorry, I don't understand, for users, it shouldn't let users to determine what's regex using here, since we litterally didn't know how do u using regex in your lib.

As an users, I just can assume you are trying to replace the varaible which is `__version__` in my `alfred/version.py`, and then replace it's value then save it as text, isn't it?

Here is my version.py:

```
from datetime import datetime

major_num = 2

__version__ = '3.0.1'
short_version = __version__
```

what else need to make it suitable for your config?

**Comment by mbarkhau** [comment]
Yes, your pattern is wrong. It uses double quotes. Try single quotes.

**Comment by jinfagang** [comment]
@mbarkhau Like I said, it doesn't update my file:

<img width="831" alt="image" src="https://user-images.githubusercontent.com/21303438/198215567-85c0a151-620c-4416-9a20-f2483b66e06a.png">

**Comment by jinfagang** [comment]
What do u think further I need do here? You made a perfect lib that doesn't work at all. I add quates, the version **jsut doesn't update**!!!!!
