### ISSUE TITLE
Use toml format for examples in the readme

### ISSUE THREAD

**Issue by routerdieb** [mbarkhau/bumpver#216]
[bumpver]
current_version = "1.5.2"
version_pattern = "MAJOR.MINOR.PATCH"

[bumpver:file_patterns]
setup.py
    version="{version}",$
src/mymodule/__init__.py
    ^__version__ = "{version}"$

Yeah old syntax, this is a very bad experience if even the first example didn't work.

**Comment by routerdieb** [comment]
bumpver update --dry
WARNING - Couldn't parse bumpver.toml: Key name found without value. Reached end of line. (line 6 column 9 char 107)
ERROR   - Could not parse configuration.

**Comment by mbarkhau** [comment]
I'd be fine with switch the examples to use toml format and make the format explicit to avoid future confusion. Would you like to open a PR and make this contribution?

**Comment by mbarkhau** [comment]
Updated with `bumpver==2023.1126`.
