### ISSUE TITLE
Show env will display blanks instead of expected 0 

### ISSUE THREAD

**Issue by elfgirl** [mbarkhau/bumpver#224]
bumpver, version 2023.1127

config is as follows

[bumpver]
current_version = "1.0.11+20231012.6336"
version_pattern = "MAJOR.MINOR.PATCH[+YYYY0M0D.BUILD]"

command shows
bumpver show -n --env
...
MAJOR=1
MINOR=
PATCH=11
...

0 has a python truthiness of false, so a blank is reported
src/bumpver/cli.py line 448 click.echo(f"{key.upper()}={val if val else ''}")

**Comment by elfgirl** [comment]
export $(bumpver show -n --env | xargs)

if [[ -z "$MAJOR" ]]; then export MAJOR=0; fi 
if [[ -z "$MINOR" ]]; then export MINOR=0; fi   
if [[ -z "$PATCH" ]]; then export PATCH=0; fi

Is a workaround for those needing to slice and dice the version numbers themselves,

**Comment by mbarkhau** [comment]
Nice catch. Thanks.

**Comment by mbarkhau** [comment]
In order to not break any existing scripts, I've hidden the old flag `-e/--env` and added a new one `--environ` with the expected behaviour.

The new flag is available with [`2023.1129`](https://pypi.org/project/bumpver/2023.1129/)
