### ISSUE TITLE
It is time to drop legacy Python 2

### ISSUE THREAD

**Issue by cclauss** [mbarkhau/bumpver#244]
https://github.com/mbarkhau/bumpver/blob/057cd90fd13ac7dca358e7678364bc2cbeab6f50/setup.py#L49

Python 2 died 1,774 days ago on 1/1/2020.

**Comment by mbarkhau** [comment]
I'm not opposed to this, but I'm not going to make a release that will do nothing more than cause things to break.

I've been thinking about moving over to uv (away from conda) and making it possible to easily work on the project directly out of a GH Codespace. In the course of that effort, it might not be worth the extra effort to maintain support for 2.7.
